language: php

php:
  - 7.1

before_script:
  - composer install

script:
  - composer test-ci
  - composer acceptance-test-ci

after_script:
  - vendor/bin/codacycoverage clover reports/coverage.xml
  - curl -s https://codecov.io/bash | bash
